# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-os"
client_id = "c7d9589274bf594697de64f3d64c1a55"
application_url = "https://summit-colleges-anderson-cases.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://summit-colleges-anderson-cases.trycloudflare.com/auth/callback",
  "https://summit-colleges-anderson-cases.trycloudflare.com/auth/shopify/callback",
  "https://summit-colleges-anderson-cases.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "om-ext.myshopify.com"
